version: "2"

volumes:
  gem_store_244:
    external: true

services:
  postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
  web:
    build:
      context: .
    command: bash
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - "${LOCAL_PORT}:3000"
      - "3035:3035"
    volumes:
      - /Users/landovsky/git/admin_react:/admin_react
      - gem_store_244:/gems
    depends_on:
      - postgres